enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced eXtended"
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config


[Music-Extended]
app-name = "Youtube Music"
excluded-patches = ""
included-patches = ""
version = "auto"
exclusive-patches = false
build-mode = "apk" # 'both', 'apk' or 'module'. default: apk
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"

[YouTube-Extended]
app-name = "YouTube"
excluded-patches = ""
included-patches = ""
version = "auto"
exclusive-patches = false
build-mode = "apk" # 'both', 'apk' or 'module'. default: apk
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Reddit-Extended]
excluded-patches = ""
included-patches = ""
version = "auto"
exclusive-patches = false
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
